"""Add early_claim_days, grace_period_days, expires_after_days to chores

Revision ID: 0a20ee519594
Revises: 8c9d0e1f2a3b
Create Date: 2025-12-29 23:41:10.139282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a20ee519594'
down_revision = '8c9d0e1f2a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('early_claim_days', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('grace_period_days', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('expires_after_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_column('expires_after_days')
        batch_op.drop_column('grace_period_days')
        batch_op.drop_column('early_claim_days')

    # ### end Alembic commands ###
