"""Initial migration with all 7 models

Revision ID: fe05e7ce7c54
Revises: 
Create Date: 2025-11-11 07:05:21.382729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe05e7ce7c54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('cooldown_days', sa.Integer(), nullable=True),
    sa.Column('max_claims_total', sa.Integer(), nullable=True),
    sa.Column('max_claims_per_kid', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ha_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('parent', 'kid')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_ha_user_id'), ['ha_user_id'], unique=True)

    op.create_table('chores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('recurrence_type', sa.String(length=20), nullable=True),
    sa.Column('recurrence_pattern', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('assignment_type', sa.String(length=20), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_after_hours', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("assignment_type IN ('individual', 'shared') OR assignment_type IS NULL", name='check_assignment_type'),
    sa.CheckConstraint("recurrence_type IN ('none', 'simple', 'complex') OR recurrence_type IS NULL", name='check_recurrence_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='check_reward_claim_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_claims', schema=None) as batch_op:
        batch_op.create_index('idx_reward_claims_claimed_at', ['claimed_at'], unique=False)
        batch_op.create_index('idx_reward_claims_user', ['user_id'], unique=False)

    op.create_table('chore_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chore_id', 'user_id', 'due_date', name='unique_chore_user_date')
    )
    with op.batch_alter_table('chore_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_chore_assignments_chore_user', ['chore_id', 'user_id'], unique=False)

    op.create_table('chore_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('claimed_by', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('assigned', 'claimed', 'approved', 'rejected')", name='check_instance_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chore_instances', schema=None) as batch_op:
        batch_op.create_index('idx_chore_instances_due_date', ['due_date'], unique=False)
        batch_op.create_index('idx_chore_instances_status', ['status'], unique=False)

    op.create_table('points_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('chore_instance_id', sa.Integer(), nullable=True),
    sa.Column('reward_claim_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chore_instance_id'], ['chore_instances.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reward_claim_id'], ['reward_claims.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.create_index('idx_points_history_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_points_history_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.drop_index('idx_points_history_user')
        batch_op.drop_index('idx_points_history_created_at')

    op.drop_table('points_history')
    with op.batch_alter_table('chore_instances', schema=None) as batch_op:
        batch_op.drop_index('idx_chore_instances_status')
        batch_op.drop_index('idx_chore_instances_due_date')

    op.drop_table('chore_instances')
    with op.batch_alter_table('chore_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_chore_assignments_chore_user')

    op.drop_table('chore_assignments')
    with op.batch_alter_table('reward_claims', schema=None) as batch_op:
        batch_op.drop_index('idx_reward_claims_user')
        batch_op.drop_index('idx_reward_claims_claimed_at')

    op.drop_table('reward_claims')
    op.drop_table('chores')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_ha_user_id'))

    op.drop_table('users')
    op.drop_table('rewards')
    # ### end Alembic commands ###
